import { cn } from "@/lib/utils"
import type { Metadata } from "next"
import { Inter, Lato } from "next/font/google"
import "../styles/globals.scss"

const inter = Inter({ subsets: ["latin"] })

const lato = Lato({
  subsets: ["latin"],
  variable: "--font-lato",
  weight: ["100", "700", "400", "300", "900"]
})

export const metadata: Metadata = {
  title: "Best chart",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(lato.variable, "font-lato")}>{children}</body>
    </html>
  )
}
